feat: add more of the common automation
- add more of the common automation
- ensure customized scripts/files are not overwritten

Signed-off-by: Michael Dawson <mdawson@devrus.com>

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -20,13 +20,63 @@ jobs:
     - name: Setup Go
       uses: actions/setup-go@v3
       with:
-        go-version: 1.19.x
+        go-version: 1.20.x
 
     - name: Checkout
       uses: actions/checkout@v3
 
     - name: Run Unit Tests
       run: ./scripts/unit.sh
+
+    - name: Get builders from integration.json
+      id: builders
+      run: |
+        source "${{ github.workspace }}/scripts/.util/builders.sh"
+
+        builders="$(util::builders::list "${{ github.workspace }}/integration.json")"
+        printf "Output: %s\n" "${builders}"
+        printf "builders=%s\n" "${builders}" >> "$GITHUB_OUTPUT"
+
+  integration:
+    name: Integration Tests with Builders
+    runs-on: ubuntu-22.04
+    needs: unit
+    strategy:
+      matrix:
+        builder: ${{ fromJSON(needs.unit.outputs.builders) }}
+      fail-fast: false  # don't cancel all test jobs when one fails
+    steps:
+    - name: Setup Go
+      uses: actions/setup-go@v3
+      with:
+        go-version: 1.20.x
+
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
+
+    - name: Run Integration Tests
+      run: ./scripts/integration.sh --use-token --builder ${{ matrix.builder }}
+      env:
+        GIT_TOKEN: ${{ github.token }}
+        TMPDIR: "${{ runner.temp }}"
+
+  roundup:
+    name: Integration Tests
+    if: ${{ always() }}
+    runs-on: ubuntu-22.04
+    needs: integration
+    steps:
+    - run: |
+        result="${{ needs.integration.result }}"
+        if [[ $result == "success" ]]; then
+          echo "Integration tests passed against all builders"
+          exit 0
+        else
+          echo "Integration tests failed on one or more builders"
+          exit 1
+        fi
 
   upload:
     name: Upload Workflow Event Payload
